### ISSUE TITLE
Add option to add a description on the level of a stack within a environment

### ISSUE THREAD

**Issue by mokit** [wieni/lola#10]
See mockup below: ("this is not support"-part)

```
    # Give that environment a name.
    <dev>:
        # Environment params for <stack1>
        <stack1>:
            # Override the stackname for this env. Optional, if not present lola generates one.
            name: <my-stack-dev>
            region: <aws region>
            profile: <~/.aws/credentails profile name>
            description: <this is not supported now>
            tags:
              <name-of-tag>: <value-of-tag>
              <name-of-another-tag>: <value-of-another-tag>
            terminationProtection: <true|false>
            params:
                <Param1>: <Value1>
            hooks:
                pre-deploy:
                    - preDeploy

**Comment by spoit** [comment]
While not unfeasable, the description is part of the template body (~ cloudformation file) and not a separate field (like tags) in the api calls. 

That means we would have to

* find a good parser for cloudformation template ('js-yaml` alone can't do it because of the !Sub stuff that's not default yaml)
* parse the body, replace the description if necessary
* reparse the result to yaml/json

Is gonna take some time.. do it?

**Comment by mokit** [comment]
Will close this one - not that important.
